spring:
    application:
        name: simple-eureka-service
server: 
    port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    client:
      serviceUrl:
        defaultZone: http://127.0.0.1:8761/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
